default:
    image: google/cloud-sdk:alpine
    before_script:
        - echo $GCP_SERVICE_CREDS > test3-342207-4d286b4f59fe.json
        - gcloud config set project test3-342207
        - gcloud auth activate-service-account --key-file test3-342207-4d286b4f59fe.json

build:
    stage: build
    script:
        - gcloud builds submit --tag eu.gcr.io/test3-342207/test3:${CI_COMMIT_SHA}

deploy:
    stage: deploy
    script:
        - gcloud run deploy test3 --image eu.gcr.io/test3-342207/test3:${CI_COMMIT_SHA} --platform managed --region europe-north1 --allow-unauthenticated
        